# Generated by Django 5.2.5 on 2025-08-08 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blgo',
            new_name='Blog',
        ),
    ]
